version: '2'
services:
    api:
        container_name: api
        image: allenyang79/account-manager
        build:
            context: api/.
            dockerfile: Dockerfile
        command: bash scripts/run-uwsgi-server.sh
        expose:
            - "5000"
        environment:
            - "ENV=production"
            - "PYTHONPATH=/srv/api"
        volumes:
            - "./api:/srv/api"
            - "./api/configs:/srv/api/configs"
        links:
            - db
        depends_on:
            - db
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - "80:80"
            - "5000:5000"
        volumes:
            - "./nginx/conf.d:/etc/nginx/conf.d:ro"
            - "./nginx/static:/usr/share/nginx/html:ro"
        links:
            - api
        depends_on:
            - api
    db:
        container_name: db
        image: mongo
        volumes:
          - ./db:/data/db
